### ISSUE TITLE
Dear author, I would like to ask you what are the TensorFlow and Keras versions you are using?

### ISSUE THREAD

**Issue by xiaohuqaq123** [nesl/RadHAR#13]

**Comment by xiaohuqaq123** [comment]
in this code

**Comment by thecyclone** [comment]
Please refer to: https://github.com/nesl/RadHAR/issues/6#issuecomment-1091028618

**Comment by xiaohuqaq123** [comment]
Thank you, I used TensorFlow 2.7 version, but still encountered the following error. Is it because my GPU memory is not enough?
I am using a 4070 12GB。
“tensorflow.python.framework.errors_impl.InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run _EagerConst: Dst tensor is not initialized.”

**Comment by thecyclone** [comment]
I do not think this error is related to our code. Quick googling says that this error is usually caused due to incompatible TensorFlow and CUDA versions, or insufficient GPU memory, or driver issues.
