### ISSUE TITLE
How to use the code from radar lab to capture the point cloud data?

### ISSUE THREAD

**Issue by Carbord** [nesl/RadHAR#2]
Hello, your work is impressive and we  also want to use the TI mmWave radar to collecte some raw point cloud data. However, while using the ROS package developed by radar-lab, we are not so familiar with that and don't know how to capture the message as well as how to write it to a txt file. I wonder if you are kind to provide some instructions about using the above  ROS package to attain the txt file in this repository. Looking forward to your reply, thanks!

**Comment by kingsoftech** [comment]
you can capture the messages by saving the bag file as .txt 
rostopic echo -b bag_file.bag -p /topic_name > Txt_name.txt
