### ISSUE TITLE
slowness on voxelization of 3D points

### ISSUE THREAD

**Issue by Tahir7044** [nesl/RadHAR#4]
voxel function taking so much time due unnecessary looping for coordinate mapping(scaling). the function taking O(N^3) time to scale all the 3D points which slow the over all performance. I have optimise the voxel function to time complexity O(NlogN) but i dont know how to contribute since I am beginner to open source.

**Comment by thecyclone** [comment]
Hi Tahir7044,

Thank you for your interest in our work. However, we are not actively managing or updating this repository. You can make a fork and update the voxelization code there. Thanks!

**Comment by Tahir7044** [comment]
okay thanks @thecyclone
