### ISSUE TITLE
Are there any preprocess methods adopted before voxelization?

### ISSUE THREAD

**Issue by aric0103** [nesl/RadHAR#5]
Hi there! Your work is awe-inspiring, and the codes are pretty clear. I have some questions about the preprocesses. Have you adopted some preprocess methods such as CFAR, clustering algorithms to remove the 3D points caused by static background and just preserve the points from body movement? I also checked the ROS package you mentioned, and there is also no information about this. I am trying to collect some points cloud using TI radar, but I find many noisy points. Could you give me some tips to set the radar parameters to collect such nice data if the dataset is not processed?  

I am looking forward to your reply. Thank you very much.

**Comment by thecyclone** [comment]
Hi,

We have not explicitly used any preprocessing methods before voxelization. However, you can read the documentation of the ROS package that we have used as well as TI's documentation of the radar used to know more.
